const express = require('express');
const todoControllers = require('./controllers/todoControllers');
const app= express();
const ejs = require('ejs');
app.engine('.html',ejs.__express);
app.set('view engine', 'html');
app.use(express.static('./public'));
todoControllers(app);
app.listen(3000);
console.log('You are is listening Port 3000');